# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:				Mark Todd's Portfolio
tagline:			Mark Todd's Portfolio
#url:				#
#baseurl:			http://30percent.github.io/

#Postings
paginate:			3
paginate_path:		"project/page:num"
excerpt_separator:	<!--postbreak-->

# Build Settings
highlighter: pygments
#highlighter: true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.

sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:				Mark Todd
  url:				http://30percent.github.io/
  email:			ddotkram@gmail.com
  linkedin:   https://www.linkedin.com/pub/mark-todd/b9/773/349
  github:     
    link: https://github.com/30percent?tab=repositories
    user: 30percent

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/30percent/30percent.github.io

#Nav List
nav_list:
  Home: /
  About: /about/
  Archive: /archive/
  InterviewQs: /interview/
  #Resume: /resume/

archive: /archive/

#Collections
collections:
  interviewqs:
    output: true